# Generated by Django 3.0.8 on 2021-01-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210114_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_num', models.IntegerField()),
                ('cert_num', models.CharField(max_length=20)),
                ('contact_num', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier'), ('Not Selected', None)], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier'), ('Not Selected', None)], max_length=50),
        ),
    ]
