# Generated by Django 3.0.8 on 2021-01-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210119_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('courier', 'courier'), ('org_pick', 'pickup by org')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('courier', 'courier'), ('org_pick', 'pickup by org')], max_length=50),
        ),
    ]
