# Generated by Django 3.0.8 on 2021-01-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210119_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_org',
            name='contact_num',
            field=models.BigIntegerField(),
        ),
    ]
