# Generated by Django 3.0.8 on 2021-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210119_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rq_medicine',
            old_name='update',
            new_name='notified',
        ),
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('courier', 'courier'), ('org_pick', 'pickup by org')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('courier', 'courier'), ('org_pick', 'pickup by org')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rq_medicine',
            name='MedPresc',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
