# Generated by Django 3.0.8 on 2021-04-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210405_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='med_rqstd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('Not Selected', None), ('courier', 'courier')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('Not Selected', None), ('courier', 'courier')], max_length=50),
        ),
    ]
