# Generated by Django 3.0.8 on 2021-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210405_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnr_update',
            old_name='med_dispatched',
            new_name='med_rcvd',
        ),
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier'), ('Not Selected', None)], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier'), ('Not Selected', None)], max_length=50),
        ),
    ]
