# Generated by Django 3.0.8 on 2021-04-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210405_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='MedRcvd',
            field=models.BooleanField(default=False),
        ),
    ]
