# Generated by Django 3.0.8 on 2020-11-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20201014_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='MedFor',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPresc',
            field=models.ImageField(blank=True, default='', upload_to='webapp/images'),
        ),
    ]
