# Generated by Django 3.0.8 on 2020-11-20 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_auto_20201120_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_update',
            name='select_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='frm_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='to_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
