# Generated by Django 3.0.8 on 2020-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_auto_20201120_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('courier', 'courier'), ('org_pick', 'pickup by org')], max_length=50),
        ),
    ]
