# Generated by Django 3.0.8 on 2020-11-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_auto_20201120_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='rq_medicine',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
