# Generated by Django 3.0.8 on 2020-11-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_auto_20201122_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnr_update',
            name='rqst_user_email',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier')], max_length=50),
        ),
    ]
