# Generated by Django 3.0.8 on 2020-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_auto_20201122_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier')], max_length=50),
        ),
    ]
