# Generated by Django 3.0.8 on 2020-11-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_auto_20201122_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='update',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('org_pick', 'pickup by org'), ('courier', 'courier')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('org_pick', 'pickup by org'), ('courier', 'courier')], max_length=50),
        ),
    ]
