# Generated by Django 3.0.8 on 2020-11-23 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_auto_20201123_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_address',
            name='zipcode',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
