# Generated by Django 3.0.8 on 2020-10-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201003_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='pincode',
        ),
    ]
