# Generated by Django 3.0.8 on 2020-10-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20201003_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='pincode',
            new_name='zipcode',
        ),
    ]
