# Generated by Django 3.0.8 on 2020-10-04 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20201004_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_for',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='presc',
            field=models.ImageField(blank=True, default='', upload_to='static/webapp'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
