# Generated by Django 3.0.8 on 2020-10-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20201004_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='MedQuanity',
            new_name='MedQuantity',
        ),
    ]
