# Generated by Django 3.0.8 on 2020-10-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20201004_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='MedPresc',
            field=models.ImageField(blank=True, default='', upload_to='webapp/images'),
        ),
    ]
