# Generated by Django 3.0.8 on 2020-10-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20201014_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='MedPic2',
            field=models.ImageField(blank=True, default='', upload_to='static/webapp'),
        ),
    ]
