# Generated by Django 3.0.8 on 2020-10-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20201014_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='MedReason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
