# Generated by Django 3.0.8 on 2020-11-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20201118_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='MedPic',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPic2',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPresc',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
