# Generated by Django 3.0.8 on 2020-11-20 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0031_rq_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='org_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rqst_med', models.BooleanField()),
                ('mode_del', models.CharField(choices=[('courier', 'courier'), ('org_pick', 'pickup by org')], max_length=50)),
                ('frm_date', models.DateField()),
                ('to_date', models.DateField()),
                ('med_rcvd', models.BooleanField(default=False)),
                ('rq_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.rq_medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dnr_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_date', models.DateField()),
                ('med_dispatched', models.BooleanField(default=False)),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
