# Generated by Django 3.0.8 on 2020-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_dnr_update_org_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_update',
            name='med_dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='med_rcvd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier')], max_length=50),
        ),
    ]
