# Generated by Django 3.0.8 on 2020-11-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_auto_20201120_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='rqst_med',
            field=models.BooleanField(default=False),
        ),
    ]
