# Generated by Django 3.0.8 on 2020-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20201120_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='MedPic',
            field=models.ImageField(default='', upload_to='webapp/images'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPic2',
            field=models.ImageField(blank=True, default='', upload_to='webapp/images'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPresc',
            field=models.ImageField(blank=True, default='', upload_to='webapp/images'),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('courier', 'courier')], max_length=50),
        ),
    ]
