# Generated by Django 3.0.8 on 2020-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_auto_20201120_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_update',
            name='select_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='frm_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='to_date',
            field=models.DateField(default=None),
        ),
    ]
