# Generated by Django 3.0.8 on 2020-11-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_auto_20201120_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_update',
            name='frm_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='to_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
