# Generated by Django 3.0.8 on 2020-11-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_rq_medicine_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_update',
            name='select_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
