# Generated by Django 3.0.8 on 2020-11-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_applied_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnr_update',
            name='frm_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('courier', 'courier'), ('org_pick', 'pickup by org')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='dnr_update',
            name='to_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('courier', 'courier'), ('org_pick', 'pickup by org')], max_length=50),
        ),
    ]
