# Generated by Django 3.0.8 on 2020-11-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_auto_20201123_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnr_update',
            name='donor_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.dnr_address'),
        ),
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('courier', 'courier'), ('org_pick', 'pickup by org')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('courier', 'courier'), ('org_pick', 'pickup by org')], max_length=50),
        ),
    ]
