# Generated by Django 3.0.8 on 2020-11-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0056_auto_20201123_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_address',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('courier', 'courier'), ('Not Selected', None), ('org_pick', 'pickup by org')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('courier', 'courier'), ('Not Selected', None), ('org_pick', 'pickup by org')], max_length=50),
        ),
    ]
