# Generated by Django 3.0.8 on 2020-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0058_auto_20201123_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('Not Selected', None), ('courier', 'courier')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedZip',
            field=models.CharField(blank=True, default='0', max_length=6),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('org_pick', 'pickup by org'), ('Not Selected', None), ('courier', 'courier')], max_length=50),
        ),
    ]
