# Generated by Django 3.0.8 on 2021-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0059_auto_20201126_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnr_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('org_pick', 'pickup by org'), ('courier', 'courier')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPic2',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPresc',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='org_update',
            name='mode_del',
            field=models.CharField(choices=[('Not Selected', None), ('org_pick', 'pickup by org'), ('courier', 'courier')], max_length=50),
        ),
    ]
