# Generated by Django 3.0.8 on 2020-10-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='desc',
        ),
        migrations.AddField(
            model_name='medicine',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_for',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_pic',
            field=models.ImageField(default='', upload_to='static/webapp'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='presc',
            field=models.ImageField(default='', upload_to='static/webapp'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='qauntity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reason',
            field=models.CharField(default='', max_length=100),
        ),
    ]
