# Generated by Django 3.0.8 on 2020-10-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_medicine_qauntity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='med_for',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='med_pic',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='presc',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='reason',
        ),
    ]
