# Generated by Django 3.0.8 on 2020-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_medicine_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
