# Generated by Django 3.0.8 on 2020-10-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20201003_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
