# Generated by Django 3.0.8 on 2020-10-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20201004_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='pincode',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
