# Generated by Django 3.0.8 on 2020-10-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20201004_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='areacode',
            new_name='zipcode',
        ),
    ]
