# Generated by Django 3.0.8 on 2020-10-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20201004_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='address',
            new_name='MedAddress',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='pub_date',
            new_name='MedDate',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='expiry_date',
            new_name='MedExpiry',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='med_for',
            new_name='MedFor',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='med_name',
            new_name='MedName',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='med_pic',
            new_name='MedPic',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='presc',
            new_name='MedPresc',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='qauntity',
            new_name='MedQuanity',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='reason',
            new_name='MedReason',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='zipcode',
            new_name='MedZip',
        ),
    ]
