# Generated by Django 3.0.8 on 2020-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_medicine_medpic2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='MedPic',
            field=models.ImageField(default='', upload_to='webapp/images'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedPic2',
            field=models.ImageField(blank=True, default='', upload_to='webapp/images'),
        ),
    ]
